### ISSUE TITLE
Write Proof "Cumulative distribution function of the log-normal distribution"

### ISSUE THREAD

**Issue by JoramSoch** [StatProofBook/StatProofBook.github.io#150]
Possible source for the proof: ["How to derive the cdf of a lognormal distribution from its pdf"](https://stats.stackexchange.com/a/151404/270304).
Proof that could be referenced: ["Cumulative distribution function of the normal distribution"](https://statproofbook.github.io/P/norm-cdf).
Proof should be placed under this link: ["Cumulative distribution function of the log-normal distribution"](https://statproofbook.github.io/P/lognorm-cdf).

**Comment by JoramSoch** [comment]
@majapavlo

**Comment by majapavlo** [comment]
@JoramSoch this should probably be marked as done 🤞

**Comment by JoramSoch** [comment]
On your command! 😎
(solved with [707132e](https://github.com/StatProofBook/StatProofBook.github.io/commit/707132e9933b2ee42e33ccb74ccd579e0d4122e1))
