### ISSUE TITLE
Difference in linked pages

### ISSUE THREAD

**Issue by Vaisakhkm2625** [StatProofBook/StatProofBook.github.io#155]
hi,
I am only stating to learn and not familiar with probability and statistics, 
but i come across a difference is links given in this page

https://statproofbook.github.io/P/bern-var.html

keyword "Variance" is pointed to [Expected value](https://statproofbook.github.io/D/mean")
than [Variance](https://statproofbook.github.io/D/var)

I am not sure whether that is correct or not, and if i am wrong, please close this issue, otherwise please let me know, i would love to edit it and give you a pull req. or else anyone seeing this could edit it.

Anyway thanks for this amazing repo(Book), helping me a lot....

**Comment by JoramSoch** [comment]
Dear @Vaisakhkm2625,

yes, you're right. Thanks for spotting this! Feel free to make the changes and send a pull request.

Glad to hear the resource is of value to you.

Cheers, @JoramSoch.

**Comment by StatProofBook** [comment]
This has been resolved with [761b183](https://github.com/StatProofBook/StatProofBook.github.io/commit/761b183aaf0d625e469b1deb1a73ad9d92b696a3).

**Comment by Vaisakhkm2625** [comment]
Ho sorry i completely forgot about this... now when.i saw mail only i remebered this

**Comment by JoramSoch** [comment]
@Vaisakhkm2625: No worries! Feel free to commit when you have other content to share...
