### ISSUE TITLE
Proof: Mode of exponential distribution

### ISSUE THREAD

**Issue by kantundpeterpan** [StatProofBook/StatProofBook.github.io#156]
There seems to be an error in the proof for the mode of the exponential distribution.

I think, there is no need to evaluate the <img src="https://render.githubusercontent.com/render/math?math=\lim\limits_{x \rightarrow 0} f_X(x)"> (which would give <img src="https://render.githubusercontent.com/render/math?math=\lambda">).

We could directly evaluate
<img src="https://render.githubusercontent.com/render/math?math=f_X(0) = \lambda*e^{-\lambda * 0} = \lambda">.

Given that <img src="https://render.githubusercontent.com/render/math?math=0 < e^{-\lambda * x} < 1"> for <img src="https://render.githubusercontent.com/render/math?math=x>0">:

<img src="https://render.githubusercontent.com/render/math?math=f_X(x) < \lambda\ \text{ for }\ x > 0">

Therefore

<img src="https://render.githubusercontent.com/render/math?math=mode(f_X) = \underset{x}{\arg\max} f_X(x) = 0 ">

**Comment by JoramSoch** [comment]
Yes, you're right. I think I wrote this, because you can't maximize this function (the exponential PDF) in the usual way (i.e. by setting the first derivative to zero), and then I got myself confused. Anyway, thanks for correcting this!

**Comment by JoramSoch** [comment]
I've [integrated the changes](https://github.com/StatProofBook/StatProofBook.github.io/commit/a35dc91dbc75ca436a86dc32045aa6234e58e566).
