### ISSUE TITLE
Correct Proof "Probability density function of the t-distribution"

### ISSUE THREAD

**Issue by StatProofBook** [StatProofBook/StatProofBook.github.io#218]
sent from anonymous reader via e-mail

![unnamed-1](https://github.com/StatProofBook/StatProofBook.github.io/assets/54538843/8b9442d6-beb6-42b7-9518-2107965890d4)

![unnamed-2](https://github.com/StatProofBook/StatProofBook.github.io/assets/54538843/883c7091-bbfd-4cf5-bbf6-3f68b67e7962)

**Comment by JoramSoch** [comment]
This was solved with commit aaa3dd3.
