### ISSUE TITLE
Put license more prominently in the footer and in the "about" section

### ISSUE THREAD

**Issue by nichtich** [StatProofBook/StatProofBook.github.io#5]
* change license to CC-BY-SA (file `LICENSE.md`)
* link to the license via the word "open" in the footer
* add CC-BY-SA icon to the footer: https://licensebuttons.net/l/by-sa/3.0/88x31.png and link it to https://creativecommons.org/licenses/by-sa/4.0/
* add a sentence about the license at https://statproofbook.github.io/about/

**Comment by StatProofBook** [comment]
Thank you. This was fixed via commits e3b16e91c0b3028b56a35a3d0d9a3636f9a6dab0, 87e1ce66bf3a5ad7b9a7dd79577d71239e1d1fdb, 06ab9c32b6aa69edd470963563268afa336f20e2 and c69bb5aaa4fd359c3e6ad986de0a66793cf60b38.
