### ISSUE TITLE
Write Proof "Probability density function of the chi-square distribution"

### ISSUE THREAD

**Issue by JoramSoch** [StatProofBook/StatProofBook.github.io#96]
In its current form, the [Definition "Chi-square distribution"](https://statproofbook.github.io/D/chi2) is ambigous as it contains (i) a definition of the chi-square distribution from the standard normal distribution and (ii) a definition of the chi-square distribution based on its probability density function (PDF). The PDF in (ii) needs to be derived from the definition in (i), e.g. following [this proof in Wikipedia](https://en.wikipedia.org/wiki/Proofs_related_to_chi-squared_distribution#Derivation_of_the_pdf_for_k_degrees_of_freedom), and the derivation needs to be added as the [Proof "Probability density function of the chi-square distribution"](https://statproofbook.github.io/P/chi2-pdf). Then, the second version should be removed from the  [Definition "Chi-square distribution"](https://statproofbook.github.io/D/chi2).

**Comment by JoramSoch** [comment]
@kjpetrykowski

**Comment by kjpetrykowski** [comment]
@JoramSoch I will resolve this issue next week

**Comment by JoramSoch** [comment]
@kjpetrykowski: Alright, don't feel pressured...

**Comment by JoramSoch** [comment]
Done, see [here](https://statproofbook.github.io/P/chi2-pdf).
