### ISSUE TITLE
Edit Proof "Moments of the chi-square distribution"

### ISSUE THREAD

**Issue by JoramSoch** [StatProofBook/StatProofBook.github.io#97]
In the [Proof "Moments of the chi-square distribution"](https://statproofbook.github.io/P/chi2-mom),
- the [gamma function](https://en.wikipedia.org/wiki/Gamma_function) should be defined in a separate equation and
- the last two equations should be extended a bit to make the result more transparent.

**Comment by JoramSoch** [comment]
@kjpetrykowski

**Comment by kjpetrykowski** [comment]
@JoramSoch I will resolve this issue next week

**Comment by JoramSoch** [comment]
@kjpetrykowski: Alright, don't feel pressured...

**Comment by JoramSoch** [comment]
This has been solved with commit db23064.
